# Generated by Django 5.1.7 on 2025-04-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=78, max_length=15),
            preserve_default=False,
        ),
    ]
